project_id = "ocwpsanqtfubixerjive"

[functions.create-user-admin]
verify_jwt = true

[functions.import-users-batch]
verify_jwt = true

[functions.ai-chat-user]
verify_jwt = true

[functions.gerar-insight-mentoria]
verify_jwt = false

[functions.gerar-objetivos-diagnostico]
verify_jwt = true

[functions.processar-documento]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.formatar-direcional]
verify_jwt = true

[functions.atualizar-conteudos-projeto]
verify_jwt = true

[functions.parse-documento-contrato]
verify_jwt = false

[functions.parse-contrato-texto]
verify_jwt = false

[functions.gerar-metadados-material]
verify_jwt = false

[functions.extrair-texto-documento]
verify_jwt = false

[functions.organizar-backlog]
verify_jwt = false
