project_id = "ocwpsanqtfubixerjive"

[functions.ai-chat-admin]
verify_jwt = true

[functions.ai-chat-user]
verify_jwt = true

[functions.gerar-insight-mentoria]
verify_jwt = false

[functions.gerar-objetivos-diagnostico]
verify_jwt = true

[functions.processar-documento]
verify_jwt = true
