// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

// Detectar se está em domínio Lovable nativo
const isLovableDomain = 
  typeof window !== "undefined" && (
    window.location.hostname.includes("lovable.app") ||
    window.location.hostname.includes("lovableproject.com")
  );

// Para domínios próprios, usar URL absoluta do broker via domínio Lovable
const lovableAuth = createLovableAuth({
  oauthBrokerUrl: isLovableDomain 
    ? "/~oauth/initiate" 
    : "https://platafomiaplicada.lovable.app/~oauth/initiate",
});

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: { redirect_uri?: string }) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
